core_site:
  - name: fs.defaultFS
    value: hdfs://home/

hdfs_site:
  - name: dfs.nameservices
    value: home
  - name: dfs.ha.namenodes.home
    value: nn1,nn2
  - name: dfs.namenode.rpc-address.home.nn1
    value: pi1:8020 
  - name: dfs.namenode.rpc-address.home.nn2
    value: pi2:8020
  - name: dfs.namenode.http-address.home.nn1
    value: pi1:9870
  - name: dfs.namenode.http-address.home.nn2
    value: pi2:9870
  - name: dfs.namenode.shared.edits.dir
    value: qjournal://pi2:8485;pi3:8485;pi4:8485/home
  - name: dfs.client.failover.proxy.provider.home
    value: org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider
  - name: dfs.ha.fencing.methods
    value: sshfence
  - name: dfs.ha.fencing.ssh.private-key-files
    value: /home/hdfs/.ssh/id_rsa
  - name: dfs.ha.automatic-failover.enabled
    value: true
  - name: ha.zookeeper.quorum
    value: pi2:2181,pi3:2181,pi4:2181
  - name: dfs.replication
    value: 1
  - name: dfs.namenode.name.dir
    value: /data/nn/
  - name: dfs.datanode.data.dir
    value: /data/dn/
  - name: dfs.journalnode.edits.dir
    value: /data/jn/
