---
namenodes:
  hosts:
    pi1:
      mode: primary
    pi2:
      mode: secondary

datanodes:
  hosts:
    pi[2:4]:

journalnodes:
  hosts:
    pi[2:4]:

zookeepers:
  hosts:
    pi2:
      zkid: 1
    pi3:
      zkid: 2
    pi4:
      zkid: 3

hadoopnodes:
  children:
    namenodes:
    datanodes:    
    journalnodes:
