--- 
- import_tasks: base.yml
  when: base_task_was_executed is not defined

- import_tasks: hadoop.yml
  when: hadoop_task_was_executed is not defined

- name: setup data folders
  block:
  - name: create /data/nn folder
    ansible.builtin.file:
      path: /data/nn
      state: directory
      owner: hdfs
      group: hdfs
      mode: '0755'

  - name: generate workers files
    ansible.builtin.template:
      src: workers.j2
      dest: /etc/hadoop/workers
      owner: hdfs
      group: hdfs
      mode: '0644'

- name: format or bootstrap namenode
  block:
  - name: start journal nodes 
    command: /opt/hadoop/bin/hdfs --workers --daemon start journalnode
    become_user: hdfs
     
  - name: format primary namenode
    command: /opt/hadoop/bin/hdfs namenode -format -nonInteractive
    become_user: hdfs
    when: inventory_hostname == groups['namenodes'][0]
    register: result
    # 0 - when successfully format the namenode
    # 1 - when the namenode is already formatted. the format is skipped.
    failed_when: result.rc not in [0,1]

  - name: start primary namenode
    command: /opt/hadoop/bin/hdfs --daemon start namenode
    become_user: hdfs

  - name: bootstrap standby namenode
    command: /opt/hadoop/bin/hdfs namenode -bootstrapStandby -nonInteractive
    become_user: hdfs
    when: inventory_hostname != groups['namenodes'][0]
    register: result
    # 0 - when successfully format the namenode
    # 5 - when the namenode is already bootstrapped, the bootstrap is skipped
    failed_when: result.rc not in [0,5]

  - name: stop primary namenode after bootstrap the standby namenode
    command: /opt/hadoop/bin/hdfs --daemon stop namenode
    become_user: hdfs

  - name: stop journal nodes
    command: /opt/hadoop/bin/hdfs --workers --daemon stop journalnode
    become_user: hdfs

- name: initializing ha state if required
  block:
  - name: stop zkfc if running
    command: /opt/hadoop/bin/hdfs --daemon stop zkfc
    become_user: hdfs

  - name: format zkfc
    command: /opt/hadoop/bin/hdfs zkfc -formatZK -nonInteractive
    become_user: hdfs
    # if the ha state is already initialized, the return code will be 2
    register: result
    failed_when: result.rc == 1 

