--- 

- name: setup data folders
  block:
  - name: create /media/nvme/data 
    ansible.builtin.file:
      path: /media/nvme/hdfs
      state: directory
      owner: hdfs
      group: hdfs  
      mode: '0755'

  - name: link /media/nvme/hdfs to /data
    ansible.builtin.file:
      src: /media/nvme/hdfs
      dest: /data
      owner: hdfs
      group: hdfs
      state: link

  - name: create /data/nn folder
    ansible.builtin.file:
      path: /data/nn
      state: directory
      owner: hdfs
      group: hdfs
      mode: '0755'

  - name: generate work files
    ansible.builtin.template:
      src: workers.j2
      dest: /etc/hadoop/workers
      owner: hdfs
      group: hdfs
      mode: '0644'

- name: format or bootstrap namenode
  block:
  - name: start journal nodes 
    command: sudo -u hdfs sh -c "bin/hdfs --daemon status journalnode || bin/hdfs --daemon start journalnode"
     
  - name: format primary namenode
    command: sudo -u hdfs /opt/hadoop/bin/hdfs namenode -format 
    args:
      creates: /data/nn/current/VERSION
    when: inventory_hostname == groups['namenodes'][0]

  - name: bootstrap secondary namenode
    command: sudo -u hdfs /opt/hadoop/bin/hdfs namenode -bootstrapStandby
    args:
      creates: /data/nn/current/VERSION
    when: inventory_hostname != groups['namenodes'][0]

- name: initializing ha state if required
  command: sudo -u hdfs /opt/hadoop/bin/hdfs zkfc -formatZK -nonInteractive
  # if the ha state is already initialized, the return code will be 2
  register: zk_init_result
  failed_when: zk_init_result.rc == 1 
