--- 
- import_tasks: base.yml
  when: base_task_was_executed is not defined

- import_tasks: hadoop.yml
  when: hadoop_task_was_executed is not defined

- name: setup data folders
  block:
  - name: create /data/jn folder
    ansible.builtin.file:
      path: /data/jn
      state: directory
      owner: hdfs
      group: hdfs
      mode: '0755'


