--- 
- import_tasks: base.yml
- import_tasks: hadoop.yml

- name: setup data folders
  block:
  - name: create /data/jn folder
    ansible.builtin.file:
      path: /data/jn
      state: directory
      owner: hdfs
      group: hdfs
      mode: '0755'


